concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "python-runner"
  url = "http://gitlab.my_domain.com"
  token = "xspmw7zgu8pTs1bYaphQ"
  executor = "docker"
  [runners.docker]
    network_mode = "server_network"
    tls_verify = false
    image = "python:3.5.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    pull_policy = "if-not-present"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
